# Importar librerías

In [ ]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import os

# Limpieza de Datos

In [ ]:
df = pd.read_csv("../input/apartments.csv")
df.head()
#Agregar nueva área al cuadrado


#

,id,price,month,area,type,rooms,centredistance,schooldistance,clinicdistance,postofficedistance,...,restaurantdistance,collegedistance,pharmacydistance,ownership,buildingmaterial,hasparkingspace,hasbalcony,haselevator,hassecurity,hasstorageroom
0,a01d82c9529f98a54d64b9e061c9a73b,1199999,1,105,apartmentBuilding,4,5.06,1.080,0.949,0.623,...,1.054,3.062,0.335,condominium,brick,no,yes,yes,no,no
1,8373aa373dbc3fe7ca3b7434166b8766,650000,1,73,tenement,3,3.24,0.275,0.672,0.367,...,0.300,1.857,0.280,condominium,brick,no,no,no,no,no
2,7d0c31d5409caab173571cce3dcdf702,590000,1,69,blockOfFlats,3,3.94,0.139,1.336,0.926,...,0.071,0.786,0.304,condominium,brick,no,yes,no,no,yes
3,3eaa36a59b9354206703b5f6b2f2ff1d,584999,1,42,blockOfFlats,2,5.19,0.209,1.533,0.201,...,0.157,2.722,0.257,condominium,NaN,no,yes,no,no,no
4,027b30cebbc49faf3094421b741ddd56,363000,1,46,blockOfFlats,2,1.65,0.250,0.624,0.510,...,0.232,0.986,0.273,condominium,concreteSlab,no,no,no,no,yes